FROM python:3.9

RUN pip install -U pip
RUN pip install pipenv

WORKDIR /app

COPY ["Pipfile", "Pipfile.lock", "./"]

# RUN pipenv --python /home/ubuntu/anaconda3/bin/python
RUN pipenv install --system --deploy

COPY ["predict.py", "lin_reg.bin", "./"]

ENTRYPOINT ["gunicorn", "--bind=0.0.0.0:9696", "predict:app"]